
upstream wersje {
    server 127.0.0.1:8081 down;
    server 127.0.0.1:8082 ;
}

server {
error_page 404 /404.html;
error_page 500 502 503 504 /50x.html;

location = /404.html {
    internal;
}

location = /50x.html {
    internal;
}

location = /app {
	proxy_pass http://wersje;
}

    listen 80;
    server_name twoja.local;

    root /var/www/twoja;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
